[package]
name = "tinix_devices"
version = "0.1.0"
authors = ["NPEX42 <NPEX42@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pc-keyboard = "0.5.0"
x86_64 = "0.13.2"
